var name = window.prompt("Please enter your name here:");
var greetingPar = document.getElementById("greeting");
greetingPar.innerHTML += ", "  + name;
var num_1 = parseInt(window.prompt("Enter first number here"));
var num_2 = parseInt(window.prompt("Enter Second number here"));
var operand1 = document.getElementById("operand1");
var operand2 = document.getElementById("operand2");
operand1.innerHTML += num_1;
operand2.innerHTML += num_2;
var addition = document.getElementById('addition');
var subtraction = document.getElementById('subtraction');
var multiplaction = document.getElementById('multiplaction');
var division = document.getElementById('division');
var modulus = document.getElementById('modulus');
var sum = num_1 + num_2;
var difference = num_1 - num_2;
var product = num_1 * num_2;
var qoutient = num_1 / num_2;
var modresult = num_1 % num_2;  
addition.innerHTML = num_1 + " + " + num_2 + ' = ' + sum;
subtraction.innerHTML = num_1 + " - " + num_2 + ' = ' + difference;
division.innerHTML = num_1 + ' / ' + num_2 + ' = ' + qoutient;
multiplaction.innerHTML = num_1 + ' x ' + num_2 + ' = ' + product;
modulus.innerHTML = num_1 + ' % ' + num_2 + ' = ' + modresult;
