input('Halt!...Press Enter to continue')
print()
print()
def Homework_Rubrics():
    print('Rubrics:')
    print('1- Choose one of the following subjects:')
    print('Yes (Letter)')
    print('No (Argumentative essay)')
    print("Yesn't (Both)")
    print()
    print('2- Write 150 - 200 words for Yes')
    print()
    print('3- Write 350 - 400 words for No')
    print()
    print("4- Write 500 - 600 words for Yesn't")

Homework_Rubrics()
print()
print()
input('Halt!...Press enter to exit')
